version: 2.1

jobs:
  trufflehog:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: install trufflehog
          command: apk add --no-cache git && pip install gitdb2==3.0.0 trufflehog
      - run:
          name: run trufflehog
          command: trufflehog --exclude_paths trufflehog/exclude-patterns.txt --allow trufflehog/allow.json .

  docker:
    docker:
      - image: darakeon/dockery
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build
          command: make build
      - run:
          name: Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: Push
          command: make push

  static:
    docker:
      - image: python
      - image: darakeon/curriculum
    steps:
      - checkout
      - run:
          name: Dependencies
          command: pip install requests boto3
      - run:
          name: Crowler
          path: static
          command: python crowler.py

workflows:
  deploy:
    jobs:
      - trufflehog
      - docker:
          requires:
            - trufflehog
          filters:
            branches:
              only: main
      - static:
          requires:
            - docker
          filters:
            branches:
              only: main
